[tool.semantic_release]
version_variable = "__init__.py:__version__"
branch = "main"
upload_to_pypi = false
changelog_file = "CHANGELOG.md"
tag_format = "v{version}"
upload_to_release = true
build_command = ""
commit_parser = "semantic_release.commit_parser:conventional"
version_source = "commit"
allow_zero_version = true
prerelease = false