[tool.semantic_release]
version_variable = ["src/__init__.py:__version__"]
branch = "symantic-fix-5"
upload_to_pypi = false
changelog_file = "CHANGELOG.md"
tag_format = "v{version}"
upload_to_release = true
build_command = "python setup.py sdist"
commit_parser = "conventional"
version_source = "commit"
major_on_zero = false
allow_zero_version = true