[tool.semantic_release]
version_variable = ["__init__.py:__version__"]
branches.main = {pattern = "main", prerelease = false}
branches.development = {pattern = "(srf.*|feature.*|fix.*)", prerelease = false}
upload_to_pypi = false
changelog_file = "CHANGELOG.md"
tag_format = "v{version}"
upload_to_release = true
build_command = ""
commit_parser = "conventional"
version_source = "commit"
major_on_zero = false

[tool.semantic_release.remote]
token = "GH_TOKEN"