services:
  - type: web
    name: ctrlaltdelusion
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/bot/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DISCORD_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
