services:
  - type: web
    name: CtrlAltDelusion
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn web:app -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DISCORD_BOT_TOKEN
        generateValue: true
      - key: OPENAI_API_KEY
        generateValue: true
