services:
  - type: web
    name: my-python-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DISCORD_BOT_TOKEN
        generateValue: true
      - key: OPENAI_API_KEY
        generateValue: true
